# Generated by Django 3.1.4 on 2021-01-07 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import esite.track.validators
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0002_auto_20201027_2246'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAudioChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('channel_id', models.CharField(blank=True, max_length=250, null=True)),
                ('avatar_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.snekimage')),
                ('members', modelcluster.fields.ParentalManyToManyField(blank=True, null=True, related_name='pacs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, null=True)),
                ('audio_file', models.FileField(blank=True, upload_to='tracks/', validators=[esite.track.validators.validate_audio_file])),
                ('audio_channel', models.CharField(blank=True, max_length=250, null=True)),
                ('audio_format', models.CharField(blank=True, max_length=250, null=True)),
                ('audio_codec', models.CharField(blank=True, max_length=250, null=True)),
                ('audio_bitrate', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', wagtail.core.fields.StreamField([('tag', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=16, required=True)), ('significance', wagtail.core.blocks.ChoiceBlock(choices=[('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark')], icon='cup'))], icon='tag', required=True))], blank=True)),
                ('attendees', wagtail.core.fields.StreamField([('attendee', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=250, required=True))], icon='user', required=True))], blank=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('pac', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='track.projectaudiochannel')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
