# Generated by Django 2.2.13 on 2020-11-24 01:57

import modelcluster.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0002_projectaudiochannel_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectaudiochannel",
            name="users",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                null=True,
                related_name="tracks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
