# Generated by Django 2.2.13 on 2020-12-29 09:49

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0005_auto_20201201_0105"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="tags",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "tag",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "name",
                                    wagtail.core.blocks.CharBlock(
                                        max_length=16, required=True
                                    ),
                                ),
                                (
                                    "significance",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("success", "Success"),
                                            ("danger", "Danger"),
                                            ("warning", "Warning"),
                                            ("info", "Info"),
                                            ("light", "Light"),
                                            ("dark", "Dark"),
                                        ],
                                        icon="cup",
                                    ),
                                ),
                            ],
                            icon="tag",
                            required=True,
                        ),
                    )
                ],
                blank=True,
            ),
        ),
    ]
