# Generated by Django 3.1.4 on 2021-01-02 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0006_auto_20201229_1049"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectaudiochannel",
            old_name="users",
            new_name="members",
        ),
    ]
