# Generated by Django 3.1.4 on 2021-01-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0007_auto_20210102_2059"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectaudiochannel",
            name="channel_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
