# Generated by Django 3.1.4 on 2021-01-05 19:52

import modelcluster.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("track", "0008_auto_20210102_2104"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectaudiochannel",
            name="members",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, null=True, related_name="pacs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
