# Generated by Django 3.1.4 on 2021-01-08 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_auto_20210107_1442'),
        ('track', '0009_auto_20210105_2052'),
    ]

    operations = [
    ]
