# Generated by Django 3.1.4 on 2021-01-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="snekuser",
            name="password_changed",
            field=models.BooleanField(default=False),
        ),
    ]
