# Generated by Django 3.1.4 on 2020-12-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_snekuser_telegram_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snekuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
